//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buraktestediyor.Models.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class dersler
    {
        public short op_kod { get; set; }
        public string ders_kod { get; set; }
        public string ders_adi { get; set; }
        public Nullable<byte> donem { get; set; }
        public Nullable<byte> teori { get; set; }
        public Nullable<byte> pratik { get; set; }
        public Nullable<byte> hocasi { get; set; }
    
        public virtual hocalar hocalar { get; set; }
    }
}
