//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buraktestediyor.Models.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        public int no { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<short> bolkod { get; set; }
        public Nullable<byte> sinif { get; set; }
        public Nullable<byte> h_ID { get; set; }
        public System.DateTime dogum_tarihi { get; set; }
        public Nullable<byte> memleket { get; set; }
    
        public virtual bolum bolum { get; set; }
        public virtual hocalar hocalar { get; set; }
        public virtual memleket memleket1 { get; set; }
    }
}
